### ISSUE TITLE
A script that plots the performance depending on the amount of data

### ISSUE THREAD

**Issue by jstypka** [jstypka/magpie#21]
The script would train & test the algorithm for different amounts of data and plot how the performance improves

**Comment by glouppe** [comment]
This is called a "learning curve". You can find tools for that in scikit-learn. 

See http://scikit-learn.org/dev/auto_examples/model_selection/plot_learning_curve.html#example-model-selection-plot-learning-curve-py

**Comment by jstypka** [comment]
I think we might drop that finally
