### ISSUE TITLE
Split magpie into two packages

### ISSUE THREAD

**Issue by jstypka** [jstypka/magpie#54]

**Comment by kaplun** [comment]
BTW we should move the repo under the `inspirehep` organization and pick up proper license/copyright.

**Comment by jstypka** [comment]
I'm gonna split it into two (already done it actually) - one for general purpose multi-label text classification and the other one for HEP usecase with all the data and scripts that we use. Do you want to move both under `inspirehep`?

**Comment by kaplun** [comment]
Yep, as discussed IRL, would be great to move both under inspirehep organization.

**Comment by jstypka** [comment]
@kaplun yup, will finish that today :+1:
